### ISSUE TITLE
No Credentials for Authentication: Quick Start Guide for Users

### ISSUE THREAD

**Issue by MeherAyedi** [ExplorViz/docs#2]
The images under Quick Start Guide for Users, https://github.com/ExplorViz/docs/wiki/Quick-Start-Guide-for-Users is working and running
The webpage demanding a login and password, i tried with login admin and password admin and many other combination but it doesn't work

**Comment by Alexander-Krause-Glau** [comment]
Which Docker stack did you use to setup ExplorViz? Fyi: we are currently working on a complete rework of our tool that will be released shortly.

**Comment by MeherAyedi** [comment]
I followed you instruction on this page https://github.com/ExplorViz/docs/wiki/Quick-Start-Guide-for-Users for the 1.5.0 version
Below the screenshot of the result using login and password
![image](https://user-images.githubusercontent.com/36035016/157072959-bc050fbf-0b80-494a-8862-7c4b15c8eb12.png)

**Comment by Alexander-Krause-Glau** [comment]
The credentials `admin` (username)  and `password` (password) worked for me. Can you try that again? 
![grafik](https://user-images.githubusercontent.com/9912468/157269537-97fa3611-8910-4f40-9091-cbd278cf48ab.png)

A demo version of the upcoming release can be found at http://samoa.se.informatik.uni-kiel.de:8090/login

**Comment by MeherAyedi** [comment]
Thanks a lot, the credentials admin (username) and password (password) works for me also. They are the correct one.
